export interface CategoryMeta { id: string; ja: string }

export const QUICK_DRAW_CATEGORIES: CategoryMeta[] = [
  { id: 'The Eiffel Tower', ja: 'エッフェル塔' },
  { id: 'The Great Wall of China', ja: '万里の長城' },
  { id: 'The Mona Lisa', ja: 'モナ・リザ' },
  { id: 'aircraft carrier', ja: '空母' },
  { id: 'airplane', ja: 'ひこうき' },
  { id: 'alarm clock', ja: 'めざまし時計' },
  { id: 'ambulance', ja: '救急車' },
  { id: 'angel', ja: '天使' },
  { id: 'animal migration', ja: '動物の大移動' },
  { id: 'ant', ja: 'あり' },
  { id: 'anvil', ja: '金床' },
  { id: 'apple', ja: 'りんご' },
  { id: 'arm', ja: 'うで' },
  { id: 'asparagus', ja: 'アスパラガス' },
  { id: 'axe', ja: 'おの' },
  { id: 'backpack', ja: 'リュック' },
  { id: 'banana', ja: 'バナナ' },
  { id: 'bandage', ja: 'ばんそうこう' },
  { id: 'barn', ja: '納屋' },
  { id: 'baseball', ja: '野球' },
  { id: 'baseball bat', ja: '野球バット' },
  { id: 'basket', ja: 'かご' },
  { id: 'basketball', ja: 'バスケットボール' },
  { id: 'bat', ja: 'こうもり' },
  { id: 'bathtub', ja: '浴槽' },
  { id: 'beach', ja: '海辺' },
  { id: 'bear', ja: 'くま' },
  { id: 'beard', ja: 'あごひげ' },
  { id: 'bed', ja: 'ベッド' },
  { id: 'bee', ja: 'はち' },
  { id: 'belt', ja: 'ベルト' },
  { id: 'bench', ja: 'ベンチ' },
  { id: 'bicycle', ja: 'じてんしゃ' },
  { id: 'binoculars', ja: '双眼鏡' },
  { id: 'bird', ja: 'とり' },
  { id: 'birthday cake', ja: '誕生日ケーキ' },
  { id: 'blackberry', ja: 'ブラックベリー' },
  { id: 'blueberry', ja: 'ブルーベリー' },
  { id: 'book', ja: 'ほん' },
  { id: 'boomerang', ja: 'ブーメラン' },
  { id: 'bottlecap', ja: 'ボトルキャップ' },
  { id: 'bowtie', ja: '蝶ネクタイ' },
  { id: 'bracelet', ja: 'ブレスレット' },
  { id: 'brain', ja: '脳' },
  { id: 'bread', ja: 'パン' },
  { id: 'bridge', ja: '橋' },
  { id: 'broccoli', ja: 'ブロッコリー' },
  { id: 'broom', ja: 'ほうき' },
  { id: 'bucket', ja: 'バケツ' },
  { id: 'bulldozer', ja: 'ブルドーザー' },
  { id: 'bus', ja: 'バス' },
  { id: 'bush', ja: '茂み' },
  { id: 'butterfly', ja: 'ちょうちょ' },
  { id: 'cactus', ja: 'サボテン' },
  { id: 'cake', ja: 'ケーキ' },
  { id: 'calculator', ja: '電卓' },
  { id: 'calendar', ja: 'カレンダー' },
  { id: 'camel', ja: 'ラクダ' },
  { id: 'camera', ja: 'カメラ' },
  { id: 'camouflage', ja: '迷彩' },
  { id: 'campfire', ja: 'たき火' },
  { id: 'candle', ja: 'ろうそく' },
  { id: 'cannon', ja: '大砲' },
  { id: 'canoe', ja: 'カヌー' },
  { id: 'car', ja: 'くるま' },
  { id: 'carrot', ja: 'にんじん' },
  { id: 'castle', ja: '城' },
  { id: 'cat', ja: 'ねこ' },
  { id: 'ceiling fan', ja: 'シーリングファン' },
  { id: 'cell phone', ja: '携帯電話' },
  { id: 'cello', ja: 'チェロ' },
  { id: 'chair', ja: 'いす' },
  { id: 'chandelier', ja: 'シャンデリア' },
  { id: 'church', ja: '教会' },
  { id: 'circle', ja: '円' },
  { id: 'clarinet', ja: 'クラリネット' },
  { id: 'clock', ja: 'とけい' },
  { id: 'cloud', ja: 'くも' },
  { id: 'coffee cup', ja: 'コーヒーカップ' },
  { id: 'compass', ja: '方位磁針' },
  { id: 'computer', ja: 'コンピューター' },
  { id: 'cookie', ja: 'クッキー' },
  { id: 'cooler', ja: 'クーラーボックス' },
  { id: 'couch', ja: 'ソファ' },
  { id: 'cow', ja: 'うし' },
  { id: 'crab', ja: 'かに' },
  { id: 'crayon', ja: 'クレヨン' },
  { id: 'crocodile', ja: 'ワニ' },
  { id: 'crown', ja: 'おうかん' },
  { id: 'cruise ship', ja: 'クルーズ船' },
  { id: 'cup', ja: 'カップ' },
  { id: 'diamond', ja: 'ダイヤモンド' },
  { id: 'dishwasher', ja: '食器洗い機' },
  { id: 'diving board', ja: '飛び込み台' },
  { id: 'dog', ja: 'いぬ' },
  { id: 'dolphin', ja: 'イルカ' },
  { id: 'donut', ja: 'ドーナツ' },
  { id: 'door', ja: 'ドア' },
  { id: 'dragon', ja: 'ドラゴン' },
  { id: 'dresser', ja: 'たんす' },
  { id: 'drill', ja: 'ドリル' },
  { id: 'drums', ja: 'ドラム' },
  { id: 'duck', ja: 'あひる' },
  { id: 'dumbbell', ja: 'ダンベル' },
  { id: 'ear', ja: 'みみ' },
  { id: 'elbow', ja: 'ひじ' },
  { id: 'elephant', ja: 'ぞう' },
  { id: 'envelope', ja: '封筒' },
  { id: 'eraser', ja: '消しゴム' },
  { id: 'eye', ja: 'め' },
  { id: 'eyeglasses', ja: 'めがね' },
  { id: 'face', ja: '顔' },
  { id: 'fan', ja: '扇風機' },
  { id: 'feather', ja: '羽' },
  { id: 'fence', ja: '柵' },
  { id: 'finger', ja: '指' },
  { id: 'fire hydrant', ja: '消火栓' },
  { id: 'fireplace', ja: '暖炉' },
  { id: 'firetruck', ja: 'しょうぼうしゃ' },
  { id: 'fish', ja: 'さかな' },
  { id: 'flamingo', ja: 'フラミンゴ' },
  { id: 'flashlight', ja: '懐中電灯' },
  { id: 'flip flops', ja: 'ビーチサンダル' },
  { id: 'floor lamp', ja: 'フロアランプ' },
  { id: 'flower', ja: 'はな' },
  { id: 'flying saucer', ja: 'UFO' },
  { id: 'foot', ja: '足' },
  { id: 'fork', ja: 'フォーク' },
  { id: 'frog', ja: 'かえる' },
  { id: 'frying pan', ja: 'フライパン' },
  { id: 'garden', ja: '庭' },
  { id: 'garden hose', ja: 'ホース' },
  { id: 'giraffe', ja: 'キリン' },
  { id: 'goatee', ja: 'あごひげ' },
  { id: 'golf club', ja: 'ゴルフクラブ' },
  { id: 'grapes', ja: 'ぶどう' },
  { id: 'grass', ja: '草' },
  { id: 'guitar', ja: 'ギター' },
  { id: 'hamburger', ja: 'ハンバーガー' },
  { id: 'hammer', ja: 'ハンマー' },
  { id: 'hand', ja: '手' },
  { id: 'harp', ja: 'ハープ' },
  { id: 'hat', ja: '帽子' },
  { id: 'headphones', ja: 'ヘッドホン' },
  { id: 'hedgehog', ja: 'ハリネズミ' },
  { id: 'helicopter', ja: 'ヘリコプター' },
  { id: 'helmet', ja: 'ヘルメット' },
  { id: 'hexagon', ja: '六角形' },
  { id: 'hockey puck', ja: 'ホッケーパック' },
  { id: 'hockey stick', ja: 'ホッケースティック' },
  { id: 'horse', ja: 'うま' },
  { id: 'hospital', ja: '病院' },
  { id: 'hot air balloon', ja: '熱気球' },
  { id: 'hot dog', ja: 'ホットドッグ' },
  { id: 'hot tub', ja: 'ジャグジー' },
  { id: 'hourglass', ja: '砂時計' },
  { id: 'house', ja: 'いえ' },
  { id: 'house plant', ja: '観葉植物' },
  { id: 'hurricane', ja: 'ハリケーン' },
  { id: 'ice cream', ja: 'アイスクリーム' },
  { id: 'jacket', ja: 'ジャケット' },
  { id: 'jail', ja: '刑務所' },
  { id: 'kangaroo', ja: 'カンガルー' },
  { id: 'key', ja: 'かぎ' },
  { id: 'keyboard', ja: 'キーボード' },
  { id: 'knee', ja: 'ひざ' },
  { id: 'knife', ja: 'ナイフ' },
  { id: 'ladder', ja: 'はしご' },
  { id: 'lantern', ja: 'ランタン' },
  { id: 'laptop', ja: 'ノートパソコン' },
  { id: 'leaf', ja: '葉' },
  { id: 'leg', ja: '脚' },
  { id: 'light bulb', ja: '電球' },
  { id: 'lighter', ja: 'ライター' },
  { id: 'lighthouse', ja: '灯台' },
  { id: 'lightning', ja: '稲妻' },
  { id: 'line', ja: '線' },
  { id: 'lion', ja: 'ライオン' },
  { id: 'lipstick', ja: '口紅' },
  { id: 'lobster', ja: 'ロブスター' },
  { id: 'lollipop', ja: 'ペロペロキャンディ' },
  { id: 'mailbox', ja: '郵便受け' },
  { id: 'map', ja: '地図' },
  { id: 'marker', ja: 'マーカー' },
  { id: 'matches', ja: 'マッチ' },
  { id: 'megaphone', ja: 'メガホン' },
  { id: 'mermaid', ja: '人魚' },
  { id: 'microphone', ja: 'マイク' },
  { id: 'microwave', ja: '電子レンジ' },
  { id: 'monkey', ja: 'さる' },
  { id: 'moon', ja: 'つき' },
  { id: 'mosquito', ja: '蚊' },
  { id: 'motorbike', ja: 'バイク' },
  { id: 'mountain', ja: '山' },
  { id: 'mouse', ja: 'ねずみ' },
  { id: 'moustache', ja: '口ひげ' },
  { id: 'mouth', ja: '口' },
  { id: 'mug', ja: 'マグカップ' },
  { id: 'mushroom', ja: 'きのこ' },
  { id: 'nail', ja: 'くぎ' },
  { id: 'necklace', ja: 'ネックレス' },
  { id: 'nose', ja: '鼻' },
  { id: 'ocean', ja: '海' },
  { id: 'octagon', ja: '八角形' },
  { id: 'octopus', ja: 'たこ' },
  { id: 'onion', ja: '玉ねぎ' },
  { id: 'oven', ja: 'オーブン' },
  { id: 'owl', ja: 'ふくろう' },
  { id: 'paint can', ja: 'ペンキ缶' },
  { id: 'paintbrush', ja: '絵筆' },
  { id: 'palm tree', ja: 'ヤシの木' },
  { id: 'panda', ja: 'パンダ' },
  { id: 'pants', ja: 'ズボン' },
  { id: 'paper clip', ja: 'クリップ' },
  { id: 'parachute', ja: 'パラシュート' },
  { id: 'parrot', ja: 'オウム' },
  { id: 'passport', ja: 'パスポート' },
  { id: 'peanut', ja: 'ピーナッツ' },
  { id: 'pear', ja: 'なし' },
  { id: 'peas', ja: 'えんどう豆' },
  { id: 'pencil', ja: 'えんぴつ' },
  { id: 'penguin', ja: 'ペンギン' },
  { id: 'piano', ja: 'ピアノ' },
  { id: 'pickup truck', ja: 'ピックアップトラック' },
  { id: 'picture frame', ja: '額縁' },
  { id: 'pig', ja: 'ぶた' },
  { id: 'pillow', ja: '枕' },
  { id: 'pineapple', ja: 'パイナップル' },
  { id: 'pizza', ja: 'ピザ' },
  { id: 'pliers', ja: 'ペンチ' },
  { id: 'police car', ja: 'パトカー' },
  { id: 'pond', ja: '池' },
  { id: 'pool', ja: 'プール' },
  { id: 'popsicle', ja: 'アイスキャンディ' },
  { id: 'postcard', ja: 'はがき' },
  { id: 'potato', ja: 'じゃがいも' },
  { id: 'power outlet', ja: 'コンセント' },
  { id: 'purse', ja: 'ハンドバッグ' },
  { id: 'rabbit', ja: 'うさぎ' },
  { id: 'raccoon', ja: 'アライグマ' },
  { id: 'radio', ja: 'ラジオ' },
  { id: 'rain', ja: '雨' },
  { id: 'rainbow', ja: 'にじ' },
  { id: 'rake', ja: '熊手' },
  { id: 'remote control', ja: 'リモコン' },
  { id: 'rhinoceros', ja: 'サイ' },
  { id: 'rifle', ja: 'ライフル' },
  { id: 'river', ja: '川' },
  { id: 'roller coaster', ja: 'ジェットコースター' },
  { id: 'rollerskates', ja: 'ローラースケート' },
  { id: 'sailboat', ja: 'ヨット' },
  { id: 'sandwich', ja: 'サンドイッチ' },
  { id: 'saw', ja: 'のこぎり' },
  { id: 'saxophone', ja: 'サックス' },
  { id: 'school bus', ja: 'スクールバス' },
  { id: 'scissors', ja: 'はさみ' },
  { id: 'scorpion', ja: 'サソリ' },
  { id: 'screwdriver', ja: 'ドライバー' },
  { id: 'sea turtle', ja: 'ウミガメ' },
  { id: 'see saw', ja: 'シーソー' },
  { id: 'shark', ja: 'サメ' },
  { id: 'sheep', ja: 'ひつじ' },
  { id: 'shoe', ja: 'くつ' },
  { id: 'shorts', ja: '半ズボン' },
  { id: 'shovel', ja: 'シャベル' },
  { id: 'sink', ja: '流し台' },
  { id: 'skateboard', ja: 'スケートボード' },
  { id: 'skull', ja: '頭蓋骨' },
  { id: 'skyscraper', ja: '超高層ビル' },
  { id: 'sleeping bag', ja: '寝袋' },
  { id: 'smiley face', ja: '笑顔' },
  { id: 'snail', ja: 'かたつむり' },
  { id: 'snake', ja: 'へび' },
  { id: 'snorkel', ja: 'シュノーケル' },
  { id: 'snowflake', ja: '雪の結晶' },
  { id: 'snowman', ja: '雪だるま' },
  { id: 'soccer ball', ja: 'サッカーボール' },
  { id: 'sock', ja: '靴下' },
  { id: 'speedboat', ja: 'モーターボート' },
  { id: 'spider', ja: 'クモ' },
  { id: 'spoon', ja: 'スプーン' },
  { id: 'spreadsheet', ja: '表計算' },
  { id: 'square', ja: '四角形' },
  { id: 'squiggle', ja: 'ぐにゃぐにゃ線' },
  { id: 'squirrel', ja: 'リス' },
  { id: 'stairs', ja: '階段' },
  { id: 'star', ja: 'ほし' },
  { id: 'steak', ja: 'ステーキ' },
  { id: 'stereo', ja: 'ステレオ' },
  { id: 'stethoscope', ja: '聴診器' },
  { id: 'stitches', ja: '縫い目' },
  { id: 'stop sign', ja: '止まれ標識' },
  { id: 'stove', ja: 'コンロ' },
  { id: 'strawberry', ja: 'いちご' },
  { id: 'streetlight', ja: '街灯' },
  { id: 'string bean', ja: 'さやいんげん' },
  { id: 'submarine', ja: '潜水艦' },
  { id: 'suitcase', ja: 'スーツケース' },
  { id: 'sun', ja: 'たいよう' },
  { id: 'swan', ja: '白鳥' },
  { id: 'sweater', ja: 'セーター' },
  { id: 'swing set', ja: 'ブランコ' },
  { id: 'sword', ja: '剣' },
  { id: 'syringe', ja: '注射器' },
  { id: 't-shirt', ja: 'Tシャツ' },
  { id: 'table', ja: 'テーブル' },
  { id: 'teapot', ja: 'ティーポット' },
  { id: 'teddy-bear', ja: 'テディベア' },
  { id: 'telephone', ja: '電話' },
  { id: 'television', ja: 'テレビ' },
  { id: 'tennis racquet', ja: 'テニスラケット' },
  { id: 'tent', ja: 'テント' },
  { id: 'tiger', ja: 'トラ' },
  { id: 'toaster', ja: 'トースター' },
  { id: 'toe', ja: '足の指' },
  { id: 'toilet', ja: 'トイレ' },
  { id: 'tooth', ja: '歯' },
  { id: 'toothbrush', ja: '歯ブラシ' },
  { id: 'toothpaste', ja: '歯みがき粉' },
  { id: 'tornado', ja: '竜巻' },
  { id: 'tractor', ja: 'トラクター' },
  { id: 'traffic light', ja: '信号' },
  { id: 'train', ja: 'でんしゃ' },
  { id: 'tree', ja: 'き' },
  { id: 'triangle', ja: '三角形' },
  { id: 'trombone', ja: 'トロンボーン' },
  { id: 'truck', ja: 'トラック' },
  { id: 'trumpet', ja: 'トランペット' },
  { id: 'umbrella', ja: 'かさ' },
  { id: 'underwear', ja: '下着' },
  { id: 'van', ja: 'バン' },
  { id: 'vase', ja: '花びん' },
  { id: 'violin', ja: 'バイオリン' },
  { id: 'washing machine', ja: '洗濯機' },
  { id: 'watermelon', ja: 'すいか' },
  { id: 'waterslide', ja: 'ウォータースライダー' },
  { id: 'whale', ja: 'くじら' },
  { id: 'wheel', ja: '車輪' },
  { id: 'windmill', ja: '風車' },
  { id: 'wine bottle', ja: 'ワインボトル' },
  { id: 'wine glass', ja: 'ワイングラス' },
  { id: 'wristwatch', ja: '腕時計' },
  { id: 'yoga', ja: 'ヨガ' },
  { id: 'zebra', ja: 'しまうま' },
  { id: 'zigzag', ja: 'ジグザグ' },
]

export const MODEL_LABELS = QUICK_DRAW_CATEGORIES.map((category) => category.id)

export const CATEGORY_BY_ID = new Map(QUICK_DRAW_CATEGORIES.map((category) => [category.id, category]))

export const CHILD_PRESET_IDS = [
  'cat',
  'dog',
  'rabbit',
  'bear',
  'bird',
  'butterfly',
  'cow',
  'crab',
  'crocodile',
  'dolphin',
  'duck',
  'elephant',
  'fish',
  'frog',
  'giraffe',
  'horse',
  'lion',
  'monkey',
  'octopus',
  'owl',
  'panda',
  'penguin',
  'pig',
  'shark',
  'sheep',
  'snail',
  'snake',
  'whale',
  'zebra',
  'apple',
  'banana',
  'bread',
  'broccoli',
  'carrot',
  'cookie',
  'donut',
  'grapes',
  'hamburger',
  'ice cream',
  'lollipop',
  'mushroom',
  'pear',
  'pineapple',
  'pizza',
  'strawberry',
  'watermelon',
  'airplane',
  'backpack',
  'bicycle',
  'book',
  'bus',
  'car',
  'chair',
  'clock',
  'cloud',
  'crown',
  'door',
  'firetruck',
  'flower',
  'house',
  'key',
  'moon',
  'pencil',
  'rainbow',
  'scissors',
  'shoe',
  'soccer ball',
  'star',
  'sun',
  'train',
  'tree',
  'umbrella',
] as const satisfies readonly string[]

export function categoryLabelJa(id: string): string {
  return CATEGORY_BY_ID.get(id)?.ja ?? id
}

export function choosePrompt(enabledIds: string[], usedIds: string[], random = Math.random): string | null {
  if (enabledIds.length === 0) return null
  const used = new Set(usedIds)
  let candidates = enabledIds.filter((id) => !used.has(id))
  if (candidates.length === 0) candidates = enabledIds
  const index = Math.min(candidates.length - 1, Math.floor(Math.max(0, random()) * candidates.length))
  return candidates[index] ?? null
}
